name: Build yq Android

on:
  push:
    workflow_dispatch:  # 支持手动触发

jobs:
  build:
    name: Build yq for Android
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的 Git 历史

    - name: Clone yq repository
      run: git clone https://github.com/mikefarah/yq.git  # 克隆 yq 仓库

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # 使用 Go 1.21

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25b
        add-to-path: false
        local-cache: false

    - name: Get dependencies
      run: |
        cd yq  # 进入到 yq 仓库目录
        go get -v -t -d ./...  # 获取 Go 依赖包

    - name: Build yq for Android
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        cd yq  # 进入 yq 项目目录
        mkdir -p bin
        CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin
        # 编译适用于 ARM64 架构的二进制文件
        CGO_ENABLED=1 CC=${CC}/aarch64-linux-android33-clang GOARCH=arm64 GOOS=android go build -tags yq_toml -tags yq_xml -tags yq_json -ldflags "-s -w" -o bin/yq_android_arm64
        # 编译适用于 ARM 架构的二进制文件
        CGO_ENABLED=1 CC=${CC}/armv7a-linux-androideabi33-clang GOARCH=arm GOARM=7 GOOS=android go build -tags yq_toml -tags yq_xml -tags yq_json -ldflags "-s -w" -o bin/yq_android_arm

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ success() }}  # 只有在成功时上传产物
      with:
        name: yq-artifact
        path: yq/bin/  # 上传编译后的二进制文件

  upload-prerelease:
    if: ${{ github.ref_type=='branch' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: yq-artifact
          path: bin/

      - name: Upload to GitHub as prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          files: |
            bin/yq_*
          prerelease: true
          generate_release_notes: true
