name: Build yq for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 获取仓库的代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # 3. 编译 yq
      - name: Build yq for Android (ARM64)
        run: |
          git clone https://github.com/mikefarah/yq.git
          cd yq
          GOOS=android GOARCH=arm64 go build -o yq

      # 4. 打包编译好的文件
      - name: Archive compiled yq
        run: |
          mkdir -p artifacts
          mv yq artifacts/
          tar -czvf yq-android-arm64.tar.gz -C artifacts yq

      # 5. 上传编译好的二进制文件作为 Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yq-android-arm64
          path: yq-android-arm64.tar.gz
